/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tictactoe;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author H.P. Asela
 */
public class DifficultySelectionForm extends javax.swing.JFrame {

    /**
     * Creates new form DifficultySelectionForm
     */
    String playername;
    public DifficultySelectionForm() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EasyB = new javax.swing.JRadioButton();
        HardB = new javax.swing.JRadioButton();
        NextB = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        ExtremelyHardB = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 255, 51));
        setPreferredSize(new java.awt.Dimension(289, 326));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Select Difficutly:");

        EasyB.setText("Easy");
        EasyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyBActionPerformed(evt);
            }
        });

        HardB.setText("Medium");
        HardB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardBActionPerformed(evt);
            }
        });

        NextB.setText("Next");
        NextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        ExtremelyHardB.setText("Hard");
        ExtremelyHardB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtremelyHardBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter Your Name:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HardB)
                            .addComponent(EasyB)
                            .addComponent(ExtremelyHardB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(Back)
                        .addGap(26, 26, 26)
                        .addComponent(NextB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EasyB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HardB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExtremelyHardB)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextB)
                    .addComponent(Back))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().trim().length()!=0 &&(EasyB.isSelected()||HardB.isSelected()|| ExtremelyHardB.isSelected())){
        GUI gui = new GUI();
        gui.name=jTextField1.getText();
        gui.gameMode=1;
        if (EasyB.isSelected()) {
            this.setVisible(false);
            
            gui.setVisible(true);
            gui.diff = 1;
        } /*else if (MediumB.isSelected()) {
             this.setVisible(false);
           
            gui.setVisible(true);
            gui.diff = 2;
        }*/ else if (HardB.isSelected()) {
             this.setVisible(false);
            
            gui.setVisible(true);
            gui.diff = 3;
        } 
         else if (ExtremelyHardB.isSelected()) {
             this.setVisible(false);
           
            gui.setVisible(true);
            gui.diff = 4;
        } }
        else {
            showMessageDialog(null, "Please Fill The Relevant Fields!!!");
        }
    }//GEN-LAST:event_NextBActionPerformed

    private void EasyBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyBActionPerformed
        // TODO add your handling code here:
        //MediumB.setSelected(false);
        HardB.setSelected(false);
        ExtremelyHardB.setSelected(false);
    }//GEN-LAST:event_EasyBActionPerformed

    private void HardBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardBActionPerformed
        // TODO add your handling code here:
        EasyB.setSelected(false);
        //MediumB.setSelected(false);
        ExtremelyHardB.setSelected(false);
    }//GEN-LAST:event_HardBActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomePage homepage = new HomePage();
        homepage.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void ExtremelyHardBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtremelyHardBActionPerformed
        // TODO add your handling code here:
        EasyB.setSelected(false);
        //MediumB.setSelected(false);
        HardB.setSelected(false);
        
    }//GEN-LAST:event_ExtremelyHardBActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JRadioButton EasyB;
    private javax.swing.JRadioButton ExtremelyHardB;
    private javax.swing.JRadioButton HardB;
    private javax.swing.JButton NextB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
