/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tictactoe;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author H.P. Asela
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        computerbutton = new javax.swing.JRadioButton();
        networkbutton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Two_playerButton = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(289, 326));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("    Enter The Mode You Want To Play With:");
        jLabel2.setMaximumSize(new java.awt.Dimension(268, 114));
        jLabel2.setPreferredSize(new java.awt.Dimension(268, 114));

        computerbutton.setText("Computer");
        computerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerbuttonActionPerformed(evt);
            }
        });

        networkbutton.setText("Network");
        networkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkbuttonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Two_playerButton.setText("Two Players");
        Two_playerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Two_playerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(networkbutton)
                            .addComponent(computerbutton)
                            .addComponent(Two_playerButton))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(computerbutton)
                .addGap(18, 18, 18)
                .addComponent(networkbutton)
                .addGap(18, 18, 18)
                .addComponent(Two_playerButton)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(rootPane, "Are You Sure?", "Exit Game.", JOptionPane.YES_NO_OPTION, 1);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void computerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerbuttonActionPerformed
        // TODO add your handling code here:
        networkbutton.setSelected(false);
        Two_playerButton.setSelected(false);

    }//GEN-LAST:event_computerbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        
        
        if (computerbutton.isSelected() || networkbutton.isSelected()|| Two_playerButton.isSelected()) {
            if (computerbutton.isSelected()) {
                this.setVisible(false);
                DifficultySelectionForm newform = new DifficultySelectionForm();
                newform.setVisible(true);
                System.out.println(newform.playername);
            }
        
            else if( Two_playerButton.isSelected()){
            this.setVisible(false);
            Two_players tp=new Two_players();
            tp.setVisible(true);
        }
        else if( networkbutton.isSelected()){
            this.setVisible(false);
            MultiplayerForm MP=new MultiplayerForm();
            MP.setVisible(true);
        }}
        else{
            showMessageDialog(null, "Please Fill The Relevant Fields!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void networkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkbuttonActionPerformed
        // TODO add your handling code here:
        computerbutton.setSelected(false);
        Two_playerButton.setSelected(false);
    }//GEN-LAST:event_networkbuttonActionPerformed

    private void Two_playerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Two_playerButtonActionPerformed
        // TODO add your handling code here:
        computerbutton.setSelected(false);
        networkbutton.setSelected(false);
    }//GEN-LAST:event_Two_playerButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Two_playerButton;
    private javax.swing.JRadioButton computerbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton networkbutton;
    // End of variables declaration//GEN-END:variables
}
